[package]
name = "wasm_checkers_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# compilation configs
[lib]
crate-type = ["cdylib"]

[target.wasm32-unknown-unknown]

[dependencies]
